# Generated by Django 5.0.6 on 2024-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="photo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
