# Generated by Django 5.0.6 on 2024-09-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_books_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="photo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
